service:
  type: NodePort
  port: 80

ingress:
  globalStaticIpName: bblfsh-play-production
  hostname: play.bblf.sh

affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: app
              operator: In
              values:
                #This value depends of the HELM_RELEASE defined in .travis.yml should be ${HELM_RELEASE}-${CHART_NAME}
                - bblfsh-web-bblfsh-web
        topologyKey: kubernetes.io/hostname

replicaCount: 2

nodeSelector:
  cloud.google.com/gke-nodepool: default-pool

bblfshd-sidecar:
  image:
    tag: v2.11.8
  drivers:
    languages:
      python:
        repository: bblfsh/python-driver
        tag: v2.8.0
      java:
        repository: bblfsh/java-driver
        tag: v2.6.0
      javascript:
        repository: bblfsh/javascript-driver
        tag: v2.6.0
      bash:
        repository: bblfsh/bash-driver
        tag: v2.4.0
      ruby:
        repository: bblfsh/ruby-driver
        tag: v2.5.0
      go:
        repository: bblfsh/go-driver
        tag: v2.5.0
      php:
        repository: bblfsh/php-driver
        tag: v2.7.0
      csharp:
        repository: bblfsh/csharp-driver
        tag: v1.4.0
