language: go

services:
  - docker

sudo: required

go:
  - 1.11.x

before_install:
  - . $HOME/.nvm/nvm.sh
  - nvm install 8
  - nvm use 8
  - npm install -g yarn

stages:
  - name: test
  - name: release
    if: tag IS present

jobs:
  include:
    - name: 'Tests'
      stage: test
      script:
        - make validate-commit
        - make lint
        - make test-frontend
        - make test-coverage
    - name: 'Release'
      stage: release
      script:
        - make packages
        - DOCKER_PUSH_LATEST=true make docker-push
      deploy:
        provider: releases
        api_key: $GITHUB_TOKEN
        file_glob: true
        file: build/*.tar.gz
        skip_cleanup: true
        on:
          tags: true
          go: 1.11.x
