[prune]
  go-tests = true
  unused-packages = true
  non-go = true

[[constraint]]
  name = "gopkg.in/bblfsh/sdk.v1"
  version = "^1.16.0"

[[constraint]]
  name = "gopkg.in/bblfsh/client-go.v3"
  version = "^3.1.0"
